services:
  - name: mockx-backend
    type: web
    env: docker
    repo: https://github.com/shundev23/MockX
    plan: free
    region: oregon
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mockx-db
          property: connectionString